### ISSUE TITLE
Erro na escrita na opção de mudar a versão para português

### ISSUE THREAD

**Issue by pancesar** [MarcoBruno/siteAb2015#12]
O site está com a opção de internacionalização para português escrita de forma errada. Está mostrando "Vesão Portugês", invés de ser "Versão Português". 

Isso acontece independente de resolução.

Veja imagem abaixo:

![linknameerrado](https://cloud.githubusercontent.com/assets/12283126/7524439/43c48a96-f4d8-11e4-8fd8-459e075362e6.png)

**Comment by vieiragabriel** [comment]
Ajustado

**Comment by vieiragabriel** [comment]
Ajustado

**Comment by vieiragabriel** [comment]
Ajustado
