### ISSUE TITLE
Adicionar links para as imagens dos Apoiadores

### ISSUE THREAD

**Issue by rcursino** [MarcoBruno/siteAb2015#7]
Nenhuma das imagens dos Apoiadores tem link para os sites dos mesmos. Apenas o patrocinador tem link atualmente.

![screen shot 2015-05-07 at 2 33 05 am](https://cloud.githubusercontent.com/assets/2363171/7509011/74a63ed8-f461-11e4-9dcc-70434bba9a3f.png)

**Comment by vieiragabriel** [comment]
Poutz q gafe!
Ajustado.
